### PR TITLE
Update QRCodeReaderPlugin.java

### PR DESCRIPTION
**Pull request by cstsortan**
Actually I think there's no need to query the platform version

### CODE REVIEW

**Comment by villela** [comment]
That would only work if the min api level is 23, current min is 16

**Comment by cstsortan** [comment]
Actually that method checkSelfPermissions() is configured to always return true if <23 because the user has accepted permissions before installing the app. If you want try to test it with your phone.

**Comment by villela** [comment]
It will return true with the permission set in the manifest but it is a runtime check, the compiler does not know that and marks activity.requestPermissions as a invalid call.

**Comment by villela** [comment]
nevermind, you are correct, I was checking the commit snipet in the wrong context, I'll merge it

**Comment by cstsortan** [comment]
I wish I could help more, for the iOS version too, but I am clueless xD

**Pull request merged**
